package com.example.postadd.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.postadd.bean.Bean;
import com.example.postadd.bean.DataBean;

import com.example.postadd.db.BeanDao;
import com.example.postadd.db.DataBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig beanDaoConfig;
    private final DaoConfig dataBeanDaoConfig;

    private final BeanDao beanDao;
    private final DataBeanDao dataBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        beanDaoConfig = daoConfigMap.get(BeanDao.class).clone();
        beanDaoConfig.initIdentityScope(type);

        dataBeanDaoConfig = daoConfigMap.get(DataBeanDao.class).clone();
        dataBeanDaoConfig.initIdentityScope(type);

        beanDao = new BeanDao(beanDaoConfig, this);
        dataBeanDao = new DataBeanDao(dataBeanDaoConfig, this);

        registerDao(Bean.class, beanDao);
        registerDao(DataBean.class, dataBeanDao);
    }
    
    public void clear() {
        beanDaoConfig.clearIdentityScope();
        dataBeanDaoConfig.clearIdentityScope();
    }

    public BeanDao getBeanDao() {
        return beanDao;
    }

    public DataBeanDao getDataBeanDao() {
        return dataBeanDao;
    }

}
